[bloodtype]
bloodtypes = [
  'ヴァイスリージェント系',
  'エーピーインディ系',
  'キングマンボ系',
  'グレイソヴリン系',
  'サドラーズウェルズ系',
  'サンデーサイレンス系',
  'ストックウエル系',
  'セントサイモン系',
  'ターントゥ系',
  'ダマスカス系',
  'ダンチヒ系',
  'ディープインパクト系',
  'ナスルーラ系',
  'ニアークティック系',
  'ノーザンダンサー系',
  'ハイペリオン系',
  'ハビタット系',
  'ハンプトン系',
  'ファイントップ系',
  'フェアウエイ系',
  'フォーティナイナー系',
  'プリンスリーギフト系',
  'ヘイロー系',
  'ボールドルーラー系',
  'マイバブー系',
  'マッチェム系',
  'ミスタープロスペクター系',
  'リボー系',
  'ロベルト系',
  'レッドゴッド系',
  'Pサンデー系',
  'Lサンデー系',
  'Dサンデー系',
  'Tサンデー系',
  'リファール系',
  'ネイティヴダンサー系',
  'エクリプス系',
  'スターリング系',
  'ネヴァーベンド系',
  'ヌレイエフ系'
]

[mainbloodtypes]

  [mainbloodtypes.'エクリプス系']
  stallions = [
    'Monsun'
  ]

  [mainbloodtypes.'サンデーサイレンス系']
  stallions = [
    'アグネスタキオン',
    'アドマイヤオーラ',
    'アドマイヤジャパン',
    'アドマイヤボス',
    'アドマイヤマックス',
    'アンライバルド',
    'ヴィクトワールピサ',
    'オレハマッテルゼ',
    'オンファイア',
    'カネヒキリ',
    'キンシャサノキセキ',
    'ゴールドアリュール',
    'サムライハート',
    'シルクフェイマス',
    'ステイゴールド',
    'スペシャルウィーク',
    'ゼンノロブロイ',
    'ダイワメジャー',
    'ダンスインザダーク',
    'ディープインパクト',
    'ディープスカイ',
    'ディープブリランテ',
    'ナカヤマフェスタ',
    'ネオユニヴァース',
    'ハーツクライ',
    'フジキセキ',
    'ブラックタイド',
    'マーベラスサンデー',
    'マツリダゴッホ',
    'マンハッタンカフェ',
    'サンデーサイレンス'
  ]

  [mainbloodtypes.'ストックウエル系']
  stallions = [
    'Lombard'
  ]

  [mainbloodtypes.'セントサイモン系']
  stallions = [
    'アーテイアス',
    'タイトスポット',
    'Graustark',
    'Le Fabuleux',
    'Pleasant Colony',
    'Plugged Nickle',
    'Siphon',
    'Speak John',
    'Stalwart'
  ]

  [mainbloodtypes.'ターントゥ系']
  stallions = [
    'ニホンピロウイナー',
    'マナード'
  ]

  [mainbloodtypes.'ダマスカス系']
  stallions = [
    'オジジアン',
    'Cutlass'
  ]

  [mainbloodtypes.'ナスルーラ系']
  stallions = [
    'アドマイヤコジーン',
    'エアジハード',
    'サクラバクシンオー',
    'ジャッジアンジェルーチ',
    'ジャングルポケット',
    'タマモクロス',
    'テスコボーイ',
    'トニービン',
    'バゴ',
    'ビワハヤヒデ',
    'ミスターシービー',
    'ミルジョージ',
    'リードワンダー',
    'リヴリア',
    'Ahmad',
    'A.P. Indy',
    'Artichoke',
    'Avenue of Flags',
    'Bel Bolide',
    'Big Shuffle',
    'Blushing Groom',
    'Candy Stripes',
    'Capote',
    'Cozzene',
    'Dashing Blade',
    'Garde Royale',
    'General Meeting',
    'Loup Sauvage',
    'Lt. Stevens',
    'Old Trieste',
    'Potrillazo',
    'Pulpit',
    'Rahy',
    'Rainbow Quest',
    'Risen Star',
    'Riverman',
    'Runaway Groom',
    'Seattle Slew',
    'Slewpy',
    'Tsunami Slew',
    'With Approval'
  ]

  [mainbloodtypes.'ニアークティック系']
  stallions = [
    'ワイルドラッシュ',
  ]

  [mainbloodtypes.'ネイティヴダンサー系']
  stallions = [
    'キョウワアリシバ',
    'Affirmed',
    'American Post',
    'Bering',
    'Diesis',
    'Kris',
    'Laomedonte',
    'Majestic Light'
  ]

  [mainbloodtypes.'ノーザンダンサー系']
  stallions = [
    'アジュディケーティング',
    'アスワン',
    'ヴァイスリーガル',
    'エリシオ',
    'オペラハウス',
    'クロフネ',
    'ゴスホークケン',
    'コマンズ',
    'コマンダーインチーフ',
    'ジェネラス',
    'ジャイアンツコーズウェイ',
    'シャーディー',
    'シングスピール',
    'スニッツェル',
    'タヤスレミグラン',
    'ダンシングブレーヴ',
    'チーフベアハート',
    'デインヒル',
    'ノーザンテースト',
    'ノーザンディクテイター',
    'ハービンジャー',
    'パントレセレブル',
    'ファルブラヴ',
    'フサイチコンコルド',
    'フサイチリシャール',
    'フランケル',
    'フレンチデピュティ',
    'ホワイトマズル',
    'ポリッシュネイビー',
    'マルゼンスキー',
    'メイショウサムソン',
    'モガミ',
    'ヨハネスブルグ',
    'ラグビーボール',
    'ラムタラ',
    'レインボーアンバー',
    'ローエングリン',
    'ロックオブジブラルタル',
    'Alzao',
    'Belong to Me',
    'Caerleon',
    'Cape Cross',
    "Chief's Crown",
    'Danzig',
    'Dayjur',
    'Deputy Minister',
    'Desert Prince',
    'Exchange Rate',
    'Fabulous Dancer',
    'Fairy King',
    'Frankel',
    'Ghostzapper',
    "Giant's Causeway",
    'Gold Away',
    'Invincible Spirit',
    'Lyphard',
    'Marju',
    'Niniski',
    'Nijinsky',
    'Nureyev',
    'Pivotal',
    'Polish Precedent',
    "Sadler's Wells",
    'Salt Lake',
    'Storm Boot',
    'Storm Cat',
    'Summer Squall'
  ]

  [mainbloodtypes.'ハンプトン系']
  stallions = [
    'ミシシッピアン',
    'Precocious'
  ]

  [mainbloodtypes.'ファイントップ系']
  stallions = [
    'ディクタス'
  ]

  [mainbloodtypes.'フェアウエイ系']
  stallions = [
    'Ela-Mana-Mou'
  ]

  [mainbloodtypes.'ヘイロー系']
  stallions = [
    'タイキシャトル',
    'ロージズインメイ',
    'Halo'
  ]

  [mainbloodtypes.'マイバブー系']
  stallions = [
    'サクラショウリ'
  ]

  [mainbloodtypes.'マッチェム系']
  stallions = [
    'ウォーニング',
    'Honour and Glory',
    'Tiznow'
  ]

  [mainbloodtypes.'ミスタープロスペクター系']
  stallions = [
    'アグネスデジタル',
    'アドマイヤムーン',
    'アフリート',
    'ヴァーミリアン',
    'エルコンドルパサー',
    'エンドスウィープ',
    'キングカメハメハ',
    'キングズベスト',
    'サウスヴィグラス',
    'ジェイドロバリー',
    'スウェプトオーヴァーボード',
    'ティンバーカントリー',
    'フォーティナイナー',
    'マイニング',
    'マイネルラヴ',
    'Belgravia',
    'Crafty Prospector',
    'Dubai Millennium',
    'Fappiano',
    'Gold Alert',
    'Gone West',
    'Grand Slam',
    'Gulch',
    'Kingmambo',
    'Hussonet',
    'Machiavellian',
    'Miswaki',
    'Mr. Prospector',
    'Pioneerof the Nile',
    'Procida',
    'Regal Ransom',
    'Rossini',
    'Seeking the Gold',
    'Smart Strike',
    'Unbridled',
    "Unbridled's Song",
    'Vettori',
    'Woodman'
  ]

  [mainbloodtypes.'ロベルト系']
  stallions = [
    'アーネストリー',
    'グラスワンダー',
    'サンシャインフォーエヴァー',
    'シンボリクリスエス',
    'スクリーンヒーロー',
    'タニノギムレット',
    'ナリタブライアン',
    'ブライアンズタイム',
    'リアルシャダイ',
    'Dynaformer',
    'Red Ransom',
    'Silver Hawk'
  ]

[subbloodtypes]

  [subbloodtypes.'ヴァイスリージェント系']
  stallions = [
    'クロフネ',
    'フサイチリシャール',
    'フレンチデピュティ',
    'Deputy Minister',
    'Ghostzapper',
    'Salt Lake'
  ]

  [subbloodtypes.'エーピーインディ系']
  stallions = [
    'A.P. Indy',
    'Old Trieste',
    'Pulpit'
  ]

  [subbloodtypes.'キングマンボ系']
  stallions = [
    'ヴァーミリアン',
    'エルコンドルパサー',
    'キングカメハメハ',
    'キングズベスト',
    'Kingmambo'
  ]

  [subbloodtypes.'グレイソヴリン系']
  stallions = [
    'アドマイヤコジーン',
    'ジャングルポケット',
    'タマモクロス',
    'トニービン',
    'ビワハヤヒデ',
    'リードワンダー',
    'Cozzene',
    'With Approval'
  ]

  [subbloodtypes.'サドラーズウェルズ系']
  stallions = [
    'オペラハウス',
    'シングスピール',
    'フランケル',
    'メイショウサムソン',
    'ローエングリン',
    'Frankel',
    "Sadler's Wells"
  ]

  [subbloodtypes.'サンデーサイレンス系']
  stallions = [
    'サンデーサイレンス'
  ]

  [subbloodtypes.'スターリング系']
  stallions = [
    'Monsun'
  ]

  [subbloodtypes.'ストームバード系']
  stallions = [
    'ゴスホークケン',
    'ジャイアンツコーズウェイ',
    'ヨハネスブルグ',
    "Giant's Causeway",
    'Storm Boot',
    'Storm Cat',
    'Summer Squall'
  ]

  [subbloodtypes.'ストックウエル系']
  stallions = [
    'Lombard'
  ]

  [subbloodtypes.'セントサイモン系']
  stallions = [
    'アーテイアス',
    'Law Society',
    'Le Fabuleux',
    'Siphon',
    'Speak John'
  ]

  [subbloodtypes.'ターントゥ系']
  stallions = [
    'マナード'
  ]

  [subbloodtypes.'ダマスカス系']
  stallions = [
    'オジジアン',
    'Cutlass'
  ]

  [subbloodtypes.'ダンチヒ系']
  stallions = [
    'アジュディケーティング',
    'コマンズ',
    'シャーディー',
    'スニッツェル',
    'チーフベアハート',
    'デインヒル',
    'ハービンジャー',
    'ポリッシュネイビー',
    'ロックオブジブラルタル',
    'Belong to Me',
    'Cape Cross',
    "Chief's Crown",
    'Danzig',
    'Dayjur',
    'Desert Prince',
    'Exchange Rate',
    'Invincible Spirit',
    'Polish Precedent'
  ]

  [subbloodtypes.'ディープインパクト系']
  stallions = [
    'ディープインパクト',
    'ディープブリランテ'
  ]

  [subbloodtypes.'ナスルーラ系']
  stallions = [
    'Ahmad',
    'Lt. Stevens',
    'Potrillazo'
  ]

  [subbloodtypes.'ニアークティック系']
  stallions = [
    'ワイルドラッシュ',
  ]

  [subbloodtypes.'ニジンスキー系']
  stallions = [
    'ジェネラス',
    'フサイチコンコルド',
    'マルゼンスキー',
    'ラムタラ',
    'Caerleon',
    'Niniski',
    'Nijinsky'
  ]

  [subbloodtypes.'ヌレイエフ系']
  stallions = [
    'パントレセレブル',
    'Gold Away',
    'Nureyev',
    'Pivotal'
  ]

  [subbloodtypes.'ネイティヴダンサー系']
  stallions = [
    'キョウワアリシバ',
    'Affirmed',
    'American Post',
    'Bering',
    'Diesis',
    'Kris',
    'Laomedonte',
    'Majestic Light'
  ]

  [subbloodtypes.'ネヴァーベンド系']
  stallions = [
    'ミルジョージ',
    'リヴリア',
    'Dashing Blade',
    'Garde Royale',
    'Loup Sauvage',
    'Riverman'
  ]

  [subbloodtypes.'ノーザンダンサー系']
  stallions = [
    'ヴァイスリーガル',
    'エリシオ',
    'タヤスレミグラン',
    'ノーザンディクテイター',
    'ファルブラヴ',
    'ラグビーボール',
    'Fabulous Dancer',
    'Fairy King',
    'Marju'
  ]

  [subbloodtypes.'ノーザンテースト系']
  stallions = [
    'アスワン',
    'ノーザンテースト',
    'レインボーアンバー'
  ]

  [subbloodtypes.'ハイペリオン系']
  stallions = [
    'ミシシッピアン',
    'Precocious'
  ]

  [subbloodtypes.'ハビタット系']
  stallions = [
    'ニホンピロウイナー'
  ]

  [subbloodtypes.'ファイントップ系']
  stallions = [
    'ディクタス'
  ]

  [subbloodtypes.'フェアウエイ系']
  stallions = [
    'Ela-Mana-Mou'
  ]

  [subbloodtypes.'フォーティナイナー系']
  stallions = [
    'アドマイヤムーン',
    'エンドスウィープ',
    'サウスヴィグラス',
    'スウェプトオーヴァーボード',
    'フォーティナイナー',
    'Regal Ransom'
  ]

  [subbloodtypes.'プリンスリーギフト系']
  stallions = [
    'エアジハード',
    'サクラバクシンオー',
    'テスコボーイ',
    'ミスターシービー'
  ]

  [subbloodtypes.'ヘイロー系']
  stallions = [
    'タイキシャトル',
    'ロージズインメイ',
    'Halo'
  ]

  [subbloodtypes.'ボールドルーラー系']
  stallions = [
    'ジャッジアンジェルーチ',
    'Artichoke',
    'Avenue of Flags',
    'Bel Bolide',
    'Big Shuffle',
    'Capote',
    'General Meeting',
    'Risen Star',
    'Seattle Slew',
    'Slewpy',
    'Tsunami Slew'
  ]

  [subbloodtypes.'マイバブー系']
  stallions = [
    'サクラショウリ'
  ]

  [subbloodtypes.'マッチェム系']
  stallions = [
    'ウォーニング',
    'Honour and Glory',
    'Tiznow'
  ]

  [subbloodtypes.'ミスタープロスペクター系']
  stallions = [
    'アグネスデジタル',
    'アフリート',
    'ジェイドロバリー',
    'ティンバーカントリー',
    'マイニング',
    'マイネルラヴ',
    'Belgravia',
    'Crafty Prospector',
    'Dubai Millennium',
    'Fappiano',
    'Gold Alert',
    'Gone West',
    'Grand Slam',
    'Gulch',
    'Hussonet',
    'Machiavellian',
    'Miswaki',
    'Mr. Prospector',
    'Pioneerof the Nile',
    'Procida',
    'Rossini',
    'Seeking the Gold',
    'Smart Strike',
    'Unbridled',
    "Unbridled's Song",
    'Vettori',
    'Woodman'
  ]

  [subbloodtypes.'リファール系']
  stallions = [
    'コマンダーインチーフ',
    'ダンシングブレーヴ',
    'ホワイトマズル',
    'モガミ',
    'Alzao',
    'Lyphard'
  ]

  [subbloodtypes.'リボー系']
  stallions = [
    'タイトスポット',
    'Graustark',
    'Law Society',
    'Pleasant Colony',
    'Plugged Nickle',
    'Stalwart'
  ]

  [subbloodtypes.'レッドゴッド系']
  stallions = [
    'バゴ',
    'Blushing Groom',
    'Candy Stripes',
    'Rahy',
    'Rainbow Quest',
    'Runaway Groom'
  ]

  [subbloodtypes.'Dサンデー系']
  stallions = [
    'オンファイア',
    'カネヒキリ',
    'ゴールドアリュール',
    'ネオユニヴァース',
  ]

  [subbloodtypes.'Lサンデー系']
  stallions = [
    'アドマイヤボス',
    'サムライハート',
    'シルクフェイマス',
    'ディープスカイ',
    'ナカヤマフェスタ',
    'ブラックタイド',
    'マーベラスサンデー'
  ]

  [subbloodtypes.'Pサンデー系']
  stallions = [
    'アグネスタキオン',
    'アドマイヤオーラ',
    'アドマイヤマックス',
    'オレハマッテルゼ',
    'キンシャサノキセキ',
    'ダイワメジャー',
    'フジキセキ',
    'マツリダゴッホ'
  ]

  [subbloodtypes.'Tサンデー系']
  stallions = [
    'ステイゴールド',
    'スペシャルウィーク',
    'ゼンノロブロイ',
    'ダンスインザダーク',
    'ハーツクライ',
    'マンハッタンカフェ'
  ]

  [subbloodtypes.'ロベルト系']
  stallions = [
    'グラスワンダー',
    'サンシャインフォーエヴァー',
    'シンボリクリスエス',
    'スクリーンヒーロー',
    'タニノギムレット',
    'ナリタブライアン',
    'ブライアンズタイム',
    'リアルシャダイ',
    'Dynaformer',
    'Red Ransom',
    'Silver Hawk'
  ]
