[bloodtype]
bloodtypes = [
  'エーピーインディ系',
  'エンドスウィープ系',
  'キングマンボ系',
  'グレイソヴリン系',
  'サンデーサイレンス系',
  'ダマスカス系',
  'ナスルーラ系',
  'フォーティナイナー系',
  'ボールドルーラー系',
  'ミスタープロスペクター系',
  'ロベルト系',
  'プリンスリーギフト系',
  'ノーザンダンサー系',
  'ヘイロー系',
  'レッドゴッド系',
  'Pサンデー系',
  'Lサンデー系',
  'Dサンデー系',
  'Tサンデー系',
  'ヴァイスリージェント系',
  'ディープインパクト系',
  'ダンチヒ系',
  'サドラーズウェルズ系',
  'セントサイモン系',
  'リファール系',
  'ネイティヴダンサー系',
  'エクリプス系',
  'スターリング系',
  'ネヴァーベンド系',
  'ヌレイエフ系'
]

[mainbloodtypes]

  [mainbloodtypes.'エクリプス系']
  stallions = [
    'Monsun'
  ]

  [mainbloodtypes.'サンデーサイレンス系']
  stallions = [
    'アグネスタキオン',
    'アドマイヤジャパン',
    'アドマイヤマックス',
    'アンライバルド',
    'ヴィクトワールピサ',
    'ゴールドアリュール',
    'スペシャルウィーク',
    'ダンスインザダーク',
    'ディープインパクト',
    'フジキセキ',
    'ブラックタイド',
    'ネオユニヴァース',
    'アドマイヤボス',
    'ダイワメジャー',
    'カネヒキリ',
    'ディープインパクト',
    'ハーツクライ',
    'ディープブリランテ',
    'ステイゴールド',
    'サンデーサイレンス'
  ]

  [mainbloodtypes.'セントサイモン系']
  stallions = [
    'Le Fabuleux',
    'Speak John'
  ]

  [mainbloodtypes.'ダマスカス系']
  stallions = [
    'Cutlass'
  ]

  [mainbloodtypes.'ナスルーラ系']
  stallions = [
    'アドマイヤコジーン',
    'エアジハード',
    'テスコボーイ',
    'トニービン',
    'ミルジョージ',
    'Cozzene',
    'Dashing Blade',
    'Garde Royale',
    'Loup Sauvage',
    'Lt. Stevens',
    'Pulpit',
    'Rahy',
    'Rainbow Quest',
    'Risen Star',
    'Runaway Groom'
  ]

  [mainbloodtypes.'ネイティヴダンサー系']
  stallions = [
    'Affirmed',
    'American Post',
    'Bering'
  ]

  [mainbloodtypes.'ノーザンダンサー系']
  stallions = [
    'アスワン',
    'クロフネ',
    'コマンズ',
    'ジャイアンツコーズウェイ',
    'シングスピール',
    'スニッツェル',
    'ダンシングブレーヴ',
    'チーフベアハート',
    'デインヒル',
    'ノーザンテースト',
    'ハービンジャー',
    'パントレセレブル',
    'フランケル',
    'マルゼンスキー',
    'ローエングリン',
    'ロックオブジブラルタル',
    'Alzao',
    'Cape Cross',
    "Chief's Crown",
    'Deputy Minister',
    'Frankel',
    'Lyphard',
    'Nijinsky',
    'Nureyev',
    'Storm Boot',
    'Storm Cat'
  ]

  [mainbloodtypes.'ヘイロー系']
  stallions = [
    'タイキシャトル',
    'ロージズインメイ'
  ]

  [mainbloodtypes.'ミスタープロスペクター系']
  stallions = [
    'アグネスデジタル',
    'アドマイヤムーン',
    'ヴァーミリアン',
    'エルコンドルパサー',
    'キングカメハメハ',
    'サウスヴィグラス',
    'スウェプトオーヴァーボード',
    'フォーティナイナー',
    'ティンバーカントリー',
    'Crafty Prospector',
    'Dubai Millennium',
    'Fappiano',
    'Kingmambo',
    'Hussonet',
    'Machiavellian',
    'Mr. Prospector',
    'Smart Strike'
  ]

  [mainbloodtypes.'ロベルト系']
  stallions = [
    'アーネストリー',
    'グラスワンダー',
    'シンボリクリスエス',
    'タニノギムレット'
  ]

[subbloodtypes]

  [subbloodtypes.'ヴァイスリージェント系']
  stallions = [
    'クロフネ',
    'Deputy Minister'
  ]

  [subbloodtypes.'エーピーインディ系']
  stallions = [
    'Pulpit'
  ]

  [subbloodtypes.'エンドスウィープ系']
  stallions = [
    'アドマイヤムーン'
  ]

  [subbloodtypes.'キングマンボ系']
  stallions = [
    'ヴァーミリアン',
    'エルコンドルパサー',
    'キングカメハメハ',
    'Kingmambo'
  ]

  [subbloodtypes.'グレイソヴリン系']
  stallions = [
    'アドマイヤコジーン',
    'トニービン',
    'Cozzene'
  ]

  [subbloodtypes.'サドラーズウェルズ系']
  stallions = [
    'シングスピール',
    'フランケル',
    'ローエングリン'
    'Frankel'
  ]

  [subbloodtypes.'サンデーサイレンス系']
  stallions = [
    'サンデーサイレンス'
  ]

  [subbloodtypes.'スターリング系']
  stallions = [
    'Monsun'
  ]

  [subbloodtypes.'ストームバード系']
  stallions = [
    'ジャイアンツコーズウェイ',
    'Storm Boot',
    'Storm Cat'
  ]

  [subbloodtypes.'セントサイモン系']
  stallions = [
    'Le Fabuleux',
    'Speak John'
  ]

  [subbloodtypes.'ダマスカス系']
  stallions = [
    'Cutlass'
  ]

  [subbloodtypes.'ダンチヒ系']
  stallions = [
    'コマンズ',
    'スニッツェル',
    'チーフベアハート',
    'デインヒル',
    'ハービンジャー',
    'ロックオブジブラルタル',
    'Cape Cross',
    "Chief's Crown"
  ]

  [subbloodtypes.'ディープインパクト系']
  stallions = [
    'ディープインパクト',
    'ディープブリランテ'
  ]

  [subbloodtypes.'ニジンスキー系']
  stallions = [
    'マルゼンスキー',
    'Nijinsky'
  ]

  [subbloodtypes.'ヌレイエフ系']
  stallions = [
    'パントレセレブル',
    'Nureyev'
  ]

  [subbloodtypes.'ネイティヴダンサー系']
  stallions = [
    'Affirmed',
    'American Post',
    'Bering'
  ]

  [subbloodtypes.'ネヴァーベンド系']
  stallions = [
    'ミルジョージ',
    'Dashing Blade',
    'Garde Royale',
    'Loup Sauvage'
  ]

  [subbloodtypes.'ノーザンテースト系']
  stallions = [
    'アスワン',
    'ノーザンテースト'
  ]

  [subbloodtypes.'フォーティナイナー系']
  stallions = [
    'サウスヴィグラス',
    'スウェプトオーヴァーボード',
    'フォーティナイナー'
  ]

  [subbloodtypes.'プリンスリーギフト系']
  stallions = [
    'エアジハード',
    'テスコボーイ'
  ]

  [subbloodtypes.'ヘイロー系']
  stallions = [
    'タイキシャトル',
    'ロージズインメイ'
  ]

  [subbloodtypes.'ボールドルーラー系']
  stallions = [
    'Risen Star'
  ]

  [subbloodtypes.'ミスタープロスペクター系']
  stallions = [
    'アグネスデジタル',
    'ティンバーカントリー',
    'Crafty Prospector',
    'Dubai Millennium',
    'Fappiano',
    'Hussonet',
    'Machiavellian',
    'Mr. Prospector',
    'Smart Strike'
  ]

  [subbloodtypes.'レッドゴッド系']
  stallions = [
    'Rahy',
    'Rainbow Quest',
    'Runaway Groom'
  ]

  [subbloodtypes.'Lサンデー系']
  stallions = [
    'ブラックタイド',
    'アドマイヤボス'
  ]

  [subbloodtypes.'Pサンデー系']
  stallions = [
    'アドマイヤマックス',
    'ダイワメジャー',
    'フジキセキ'
  ]

  [subbloodtypes.'Dサンデー系']
  stallions = [
    'ゴールドアリュール',
    'ネオユニヴァース',
    'カネヒキリ'
  ]

  [subbloodtypes.'Tサンデー系']
  stallions = [
    'ステイゴールド',
    'スペシャルウィーク',
    'ダンスインザダーク',
    'ハーツクライ'
  ]

  [subbloodtypes.'ナスルーラ系']
  stallions = [
    'Lt. Stevens'
  ]

  [subbloodtypes.'リファール系']
  stallions = [
    'ダンシングブレーヴ',
    'Alzao',
    'Lyphard'
  ]


  [subbloodtypes.'ロベルト系']
  stallions = [
    'グラスワンダー',
    'シンボリクリスエス',
    'タニノギムレット'
  ]
